global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
 - /etc/prometheus/rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'udapeople'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
    # display ec2 instance name as target
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [__meta_ec2_public_ip]
        target_label: endpoint
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']