- name: Download prometheus binaries
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    dest: /tmp/prometheus-2.19.0.linux-amd64.tar.gz
    mode: 0755
# Extract prometheus binaries
- name: Extract prometheus binaries
  unarchive:
    src: /tmp/prometheus-2.19.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes
    creates: /tmp/prometheus-2.19.0.linux-amd64
# Copy prometheus binaries to /usr/local/bin
- name: Copy prometheus binaries to /usr/local/bin
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    remote_src: yes
    mode: 0755
# Copy prometheus promotool file to /usr/local/bin
- name: Copy prometheus promtool file to /usr/local/bin
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/promtool
    dest: /usr/local/bin/promtool
    remote_src: yes
    mode: 0755
# Create prometheus user
- name: Create prometheus user
  user:
    name: prometheus
    comment: Prometheus
    shell: /bin/false
    system: yes
- name: Make etc folder for prometheus
  become: true
  file:
    path: /etc/prometheus
    state: directory
    mode: 0755
- name: Make lib folder for prometheus
  become: true
  file:
    path: /var/lib/prometheus
    state: directory
    mode: 0755
- name: Copy consoles to /etc/prometheus
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/consoles
    dest: /etc/prometheus/consoles
    remote_src: yes
    mode: 0755  
- name: Copy console_libraries to /etc/prometheus
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/console_libraries
    dest: /etc/prometheus/console_libraries
    remote_src: yes
    mode: 0755
- name: Copy prometheus.yml to /etc/prometheus
  become: true
  copy:
    src: ./prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    mode: 0755
# Create prometheus service
- name: Create prometheus service
  become: true
  template:
    src: ./prometheus.service
    dest: /etc/systemd/system/prometheus.service
# enable and start prometheus service
- name: enable and start prometheus service
  become: true
  systemd:
    name: prometheus
    enabled: yes
    state: started
